### ISSUE TITLE
GSEA fixes to gene ranking and exercise 2

### ISSUE THREAD

**Issue by tavareshugo** [bioinformatics-core-shared-training/Bulk_RNAseq_Course_Base#23]
In exercise 2 people are getting confused about this:   
`-log10({p value}) * sign({Fold Change})`

We can probably just place the actual code in there: 
`-log10(FDR) * sign(logFC)`

Also, we need to include filtering for missing values in pvalue column earlier in the materials (so people do the same in this exercise.
Change [this line of code](https://github.com/bioinformatics-core-shared-training/Bulk_RNAseq_Course_Base/blob/65d617e9b3d944b60a956f5d443194db6339f324/Markdowns/10_Gene_set_testing.Rmd#L272) to:

```r
drop_na(GeneID, FDR, log2FoldChange) %>%
```

**Comment by TomSmithCGAT** [comment]
Agree with making columns used more consistent.

Just a word of caution though that switching from p-value to adjusted p-value (assuming that's what FDR is here) will change the ranking since it will make the ranking more dependent upon the magnitude of the fold-change. AFAIK, the first time this metric was proposed for GSEA was in [Xiao et al](https://academic.oup.com/bioinformatics/article/30/6/801/285151), where they used unadjusted p-value, though they note that an adjusted value _could_ be used.
